name: nextcloud
version: "33.0.0"
format: spdx

source:
  type: docker
  image: "library/nextcloud"
  registry: "docker.io"
  platform: "linux/amd64"

sbomify:
  component_id: "Jb1ud2xdRV5F"
  component_name: "Nextcloud"
  product_id: "isvwpwqKgKum"
