# SBOM workflow for Node.js (Docker Official)
#
# Triggers when node config is updated.
# Extracts SBOM from Docker OCI attestation (SPDX).
# Also picked up by tea-sync hourly for image digest changes.
#
# https://hub.docker.com/_/node

name: "SBOM: node"

on:
  push:
    branches:
      - master
    paths:
      - 'apps/node/config.yaml'
      - '.github/workflows/sbom-node.yml'

  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Run in dry-run mode (no upload)'
        required: false
        type: boolean
        default: false

jobs:
  build:
    uses: ./.github/workflows/sbom-builder.yml
    with:
      app: node
      dry_run: ${{ github.event.inputs.dry_run == 'true' }}
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      attestations: write
