# SBOM workflow for Eclipse Mosquitto (Docker Official)
#
# Triggers when eclipse-mosquitto config is updated.
# Extracts SBOM from Docker OCI attestation (SPDX).
# Also picked up by tea-sync hourly for image digest changes.
#
# https://hub.docker.com/_/eclipse-mosquitto

name: "SBOM: eclipse-mosquitto"

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Run in dry-run mode (no upload)'
        required: false
        type: boolean
        default: false

jobs:
  build:
    uses: ./.github/workflows/sbom-builder.yml
    with:
      app: eclipse-mosquitto
      dry_run: ${{ github.event.inputs.dry_run == 'true' }}
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      attestations: write
