# SBOM workflow for Neo4j (Docker Official)
#
# Triggers when neo4j config is updated.
# Extracts SBOM from Docker OCI attestation (SPDX).
# Also picked up by tea-sync hourly for image digest changes.
#
# https://hub.docker.com/_/neo4j

name: "SBOM: neo4j"

on:
  push:
    branches:
      - master
    paths:
      - 'apps/neo4j/config.yaml'
      - '.github/workflows/sbom-neo4j.yml'

  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Run in dry-run mode (no upload)'
        required: false
        type: boolean
        default: false

jobs:
  build:
    uses: ./.github/workflows/sbom-builder.yml
    with:
      app: neo4j
      dry_run: ${{ github.event.inputs.dry_run == 'true' }}
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      attestations: write
